import { InfluencerProfile } from "@/components/influencer/influencer-profile"
import { DashboardHeader } from "@/components/dashboard/dashboard-header"
import { notFound } from "next/navigation"

// Mock data - in a real app this would come from a database
const influencers = [
  {
    id: "1",
    name: "Ana Silva",
    username: "@anasilva_fit",
    category: "Saúde",
    followers: "125K",
    followersCount: 125000,
    engagement: "4.8%",
    engagementRate: 4.8,
    region: "São Paulo",
    profileImage: "/fitness-woman-determined.png",
    portfolioImages: ["/fitness-workout.png", "/healthy-food-still-life.png", "/woman-in-warrior-two.png"],
    description: "Especialista em fitness e nutrição, ajudando pessoas a alcançarem seus objetivos de saúde.",
    objectives:
      "Promover um estilo de vida saudável e equilibrado através de conteúdo educativo sobre exercícios, nutrição e bem-estar mental.",
    painPoints: "Falta de tempo para exercícios e alimentação saudável na rotina corrida das pessoas modernas.",
    needs: "Produtos de qualidade que facilitem a rotina fitness, suplementos confiáveis e equipamentos acessíveis.",
    howLinkupHelps:
      "Conecta com marcas de suplementos, equipamentos fitness e roupas esportivas que compartilham valores de saúde e qualidade.",
    bio: "Formada em Educação Física e Nutrição, Ana tem mais de 8 anos de experiência ajudando pessoas a transformarem suas vidas através do fitness. Seu conteúdo combina treinos práticos, receitas saudáveis e dicas de motivação.",
    location: "São Paulo, SP - Brasil",
    joinedDate: "Janeiro 2020",
    avgLikes: "5.2K",
    avgComments: "340",
    avgShares: "180",
    topCategories: ["Fitness", "Nutrição", "Bem-estar", "Motivação"],
    recentPosts: [
      {
        id: "1",
        image: "/fitness-workout.png",
        caption: "Treino de 20 minutos para fazer em casa! 💪",
        likes: "6.8K",
        comments: "423",
        date: "2 dias atrás",
      },
      {
        id: "2",
        image: "/healthy-food-still-life.png",
        caption: "Receita de smoothie proteico pós-treino 🥤",
        likes: "4.9K",
        comments: "287",
        date: "4 dias atrás",
      },
      {
        id: "3",
        image: "/woman-in-warrior-two.png",
        caption: "Yoga para relaxar depois de um dia intenso 🧘‍♀️",
        likes: "5.5K",
        comments: "356",
        date: "1 semana atrás",
      },
    ],
  },
  {
    id: "2",
    name: "Carlos Tech",
    username: "@carlostech",
    category: "Tecnologia",
    followers: "89K",
    followersCount: 89000,
    engagement: "6.2%",
    engagementRate: 6.2,
    region: "Rio de Janeiro",
    profileImage: "/tech-man.png",
    portfolioImages: ["/placeholder-96d9l.png", "/cozy-laptop-setup.png", "/diverse-tech-gadgets.png"],
    description: "Reviewer de tecnologia com foco em smartphones, laptops e gadgets inovadores.",
    objectives: "Educar sobre tecnologia e ajudar na escolha de produtos através de reviews honestos e detalhados.",
    painPoints: "Produtos de baixa qualidade no mercado e falta de informação técnica confiável para consumidores.",
    needs: "Acesso antecipado a lançamentos tecnológicos e parcerias com marcas que valorizam transparência.",
    howLinkupHelps: "Facilita parcerias com marcas de tecnologia, startups e empresas que buscam reviews autênticos.",
    bio: "Engenheiro de Software apaixonado por tecnologia. Carlos testa e analisa os mais diversos gadgets, sempre com foco na experiência real do usuário.",
    location: "Rio de Janeiro, RJ - Brasil",
    joinedDate: "Março 2019",
    avgLikes: "3.8K",
    avgComments: "245",
    avgShares: "120",
    topCategories: ["Smartphones", "Laptops", "Gadgets", "Reviews"],
    recentPosts: [
      {
        id: "1",
        image: "/cozy-laptop-setup.png",
        caption: "Review completo do novo MacBook Pro M3 📱",
        likes: "4.2K",
        comments: "312",
        date: "1 dia atrás",
      },
      {
        id: "2",
        image: "/diverse-tech-gadgets.png",
        caption: "Top 5 gadgets que mudaram minha produtividade ⚡",
        likes: "3.6K",
        comments: "198",
        date: "3 dias atrás",
      },
    ],
  },
  {
    id: "3",
    name: "Mariana Style",
    username: "@marianastyle",
    category: "Moda",
    followers: "156K",
    followersCount: 156000,
    engagement: "5.4%",
    engagementRate: 5.4,
    region: "São Paulo",
    profileImage: "/stylish-fashion-blogger.png",
    portfolioImages: ["/stylish-streetwear-outfit.png", "/street-style.png", "/fashion-accessories-collection.png"],
    description: "Consultora de moda e estilo, criando looks acessíveis para o dia a dia.",
    objectives: "Democratizar a moda e ajudar pessoas a se expressarem através do estilo pessoal.",
    painPoints: "Pressão por consumo excessivo e falta de orientação sobre como criar um guarda-roupa versátil.",
    needs: "Parcerias com marcas sustentáveis e acessíveis que valorizem a diversidade.",
    howLinkupHelps: "Conecta com marcas de moda consciente e empresas que buscam representatividade autêntica.",
    bio: "Formada em Design de Moda, Mariana acredita que estilo não tem a ver com preço, mas com personalidade. Seus looks inspiram milhares de seguidores diariamente.",
    location: "São Paulo, SP - Brasil",
    joinedDate: "Junho 2018",
    avgLikes: "7.1K",
    avgComments: "420",
    avgShares: "230",
    topCategories: ["Moda", "Estilo", "Sustentabilidade", "Diversidade"],
    recentPosts: [
      {
        id: "1",
        image: "/stylish-streetwear-outfit.png",
        caption: "Look do dia: elegante e confortável ✨",
        likes: "8.2K",
        comments: "456",
        date: "1 dia atrás",
      },
      {
        id: "2",
        image: "/street-style.png",
        caption: "Como criar 5 looks com 3 peças básicas 👗",
        likes: "6.9K",
        comments: "378",
        date: "3 dias atrás",
      },
    ],
  },
  {
    id: "4",
    name: "Pedro Games",
    username: "@pedrogames",
    category: "Games",
    followers: "203K",
    followersCount: 203000,
    engagement: "7.1%",
    engagementRate: 7.1,
    region: "Minas Gerais",
    profileImage: "/young-gamer-headset.png",
    portfolioImages: ["/ultimate-gaming-setup.png", "/game-review.png", "/esports-tournament.png"],
    description: "Streamer e reviewer de games, especializado em RPGs e jogos indie.",
    objectives: "Descobrir e promover jogos incríveis, especialmente de desenvolvedores independentes.",
    painPoints: "Saturação do mercado de games e dificuldade de jogos indie ganharem visibilidade.",
    needs: "Acesso antecipado a lançamentos e parcerias com desenvolvedores que valorizam feedback honesto.",
    howLinkupHelps: "Facilita conexões com desenvolvedores indie, publishers e marcas de hardware gaming.",
    bio: "Gamer desde os 8 anos, Pedro transformou sua paixão em profissão. Seus reviews são conhecidos pela honestidade e profundidade técnica.",
    location: "Belo Horizonte, MG - Brasil",
    joinedDate: "Setembro 2017",
    avgLikes: "12.3K",
    avgComments: "890",
    avgShares: "450",
    topCategories: ["RPG", "Indie Games", "Reviews", "Streaming"],
    recentPosts: [
      {
        id: "1",
        image: "/ultimate-gaming-setup.png",
        caption: "Setup atualizado para 2024! Que acham? 🎮",
        likes: "15.2K",
        comments: "1.2K",
        date: "2 dias atrás",
      },
      {
        id: "2",
        image: "/game-review.png",
        caption: "Review: Este indie me surpreendeu! 🌟",
        likes: "11.8K",
        comments: "743",
        date: "5 dias atrás",
      },
    ],
  },
  {
    id: "5",
    name: "Julia Travel",
    username: "@juliatravel",
    category: "Viagens",
    followers: "178K",
    followersCount: 178000,
    engagement: "4.9%",
    engagementRate: 4.9,
    region: "Global",
    profileImage: "/travel-blogger-woman-backpack.png",
    portfolioImages: ["/diverse-travel-destinations.png", "/travel-photography.png", "/travel-tips-collage.png"],
    description: "Nômade digital compartilhando dicas de viagem e destinos únicos pelo mundo.",
    objectives: "Inspirar pessoas a explorarem o mundo de forma consciente e sustentável.",
    painPoints: "Turismo de massa prejudicando destinos locais e falta de informação sobre viagem responsável.",
    needs: "Parcerias com empresas de turismo sustentável e marcas que apoiam o nomadismo digital.",
    howLinkupHelps:
      "Conecta com agências de turismo responsável, marcas de equipamentos de viagem e serviços digitais.",
    bio: "Jornalista que trocou o escritório pelo mundo. Julia já visitou 47 países e documenta cada aventura com foco em sustentabilidade e cultura local.",
    location: "Nômade Digital - Mundo",
    joinedDate: "Abril 2019",
    avgLikes: "8.7K",
    avgComments: "520",
    avgShares: "380",
    topCategories: ["Viagens", "Sustentabilidade", "Cultura", "Nomadismo"],
    recentPosts: [
      {
        id: "1",
        image: "/diverse-travel-destinations.png",
        caption: "Descobri este paraíso escondido na Tailândia 🏝️",
        likes: "12.4K",
        comments: "687",
        date: "1 dia atrás",
      },
      {
        id: "2",
        image: "/travel-photography.png",
        caption: "Dicas para fotografar como um local 📸",
        likes: "7.9K",
        comments: "423",
        date: "4 dias atrás",
      },
    ],
  },
  {
    id: "6",
    name: "Roberto Eco",
    username: "@robertoeco",
    category: "Ecologia",
    followers: "94K",
    followersCount: 94000,
    engagement: "6.8%",
    engagementRate: 6.8,
    region: "Amazonas",
    profileImage: "/environmental-activist-man-nature.png",
    portfolioImages: ["/environmental-conservation.png", "/sustainable-living-community.png", "/nature-photography-collection.png"],
    description: "Ativista ambiental promovendo sustentabilidade e conservação da natureza.",
    objectives: "Educar sobre questões ambientais e promover práticas sustentáveis no dia a dia.",
    painPoints: "Desinformação sobre mudanças climáticas e resistência a mudanças de hábitos sustentáveis.",
    needs: "Apoio de empresas verdadeiramente sustentáveis e plataformas para amplificar a mensagem ambiental.",
    howLinkupHelps: "Conecta com marcas eco-friendly, ONGs ambientais e empresas com práticas ESG genuínas.",
    bio: "Biólogo especializado em conservação, Roberto dedica sua vida à proteção do meio ambiente. Seus conteúdos combinam ciência e ativismo de forma acessível.",
    location: "Manaus, AM - Brasil",
    joinedDate: "Janeiro 2018",
    avgLikes: "6.4K",
    avgComments: "380",
    avgShares: "290",
    topCategories: ["Sustentabilidade", "Conservação", "Educação Ambiental", "Ativismo"],
    recentPosts: [
      {
        id: "1",
        image: "/environmental-conservation.png",
        caption: "A importância das florestas urbanas 🌳",
        likes: "7.8K",
        comments: "445",
        date: "2 dias atrás",
      },
      {
        id: "2",
        image: "/sustainable-living-community.png",
        caption: "5 mudanças simples para uma vida mais sustentável ♻️",
        likes: "5.9K",
        comments: "312",
        date: "1 semana atrás",
      },
    ],
  },
  {
    id: "7",
    name: "Fernanda Startup",
    username: "@fernandasstartup",
    category: "Empreendedorismo",
    followers: "142K",
    followersCount: 142000,
    engagement: "5.7%",
    engagementRate: 5.7,
    region: "São Paulo",
    profileImage: "/diverse-business-person.png",
    portfolioImages: ["/startup-office.png", "/business-meeting-collaboration.png", "/entrepreneur-presentation.png"],
    description: "Empreendedora serial e mentora, compartilhando insights sobre startups e inovação.",
    objectives: "Democratizar o conhecimento sobre empreendedorismo e inspirar novos negócios inovadores.",
    painPoints: "Falta de acesso a capital e mentoria para empreendedores iniciantes, especialmente mulheres.",
    needs: "Conexões com investidores, aceleradoras e empresas que apoiam o ecossistema de inovação.",
    howLinkupHelps:
      "Facilita parcerias com fundos de investimento, aceleradoras, empresas de tecnologia e serviços B2B.",
    bio: "CEO e fundadora de 3 startups, Fernanda é referência em empreendedorismo feminino. Já levantou mais de R$ 50M em investimentos e mentora dezenas de empreendedores.",
    location: "São Paulo, SP - Brasil",
    joinedDate: "Outubro 2019",
    avgLikes: "8.1K",
    avgComments: "560",
    avgShares: "420",
    topCategories: ["Startups", "Investimentos", "Liderança", "Inovação"],
    recentPosts: [
      {
        id: "1",
        image: "/startup-office.png",
        caption: "Como validar sua ideia de negócio em 30 dias 🚀",
        likes: "9.7K",
        comments: "678",
        date: "1 dia atrás",
      },
      {
        id: "2",
        image: "/business-meeting-collaboration.png",
        caption: "Erros que cometi no meu primeiro pitch 💡",
        likes: "7.3K",
        comments: "489",
        date: "3 dias atrás",
      },
      {
        id: "3",
        image: "/entrepreneur-presentation.png",
        caption: "Mulheres no empreendedorismo: desafios e oportunidades 👩‍💼",
        likes: "8.9K",
        comments: "612",
        date: "1 semana atrás",
      },
    ],
  },
  {
    id: "8",
    name: "Lucas Finance",
    username: "@lucasfinance",
    category: "Finanças",
    followers: "167K",
    followersCount: 167000,
    engagement: "4.3%",
    engagementRate: 4.3,
    region: "São Paulo",
    profileImage: "/financial-advisor-man-professional.png",
    portfolioImages: ["/financial-planning-meeting.png", "/investment-charts.png", "/money-education.png"],
    description: "Educador financeiro ajudando pessoas a organizarem suas finanças e investirem melhor.",
    objectives: "Democratizar a educação financeira e ajudar pessoas a alcançarem independência financeira.",
    painPoints: "Baixa educação financeira da população e produtos financeiros complexos e caros.",
    needs: "Parcerias com fintechs, corretoras e empresas que oferecem produtos financeiros transparentes.",
    howLinkupHelps: "Conecta com instituições financeiras, fintechs, corretoras e empresas de educação financeira.",
    bio: "Economista e planejador financeiro certificado, Lucas simplifica o mundo dos investimentos. Já ajudou mais de 50 mil pessoas a organizarem suas finanças.",
    location: "São Paulo, SP - Brasil",
    joinedDate: "Fevereiro 2018",
    avgLikes: "7.2K",
    avgComments: "430",
    avgShares: "320",
    topCategories: ["Investimentos", "Planejamento", "Educação Financeira", "Economia"],
    recentPosts: [
      {
        id: "1",
        image: "/financial-planning-meeting.png",
        caption: "Como montar uma reserva de emergência 💰",
        likes: "8.5K",
        comments: "523",
        date: "2 dias atrás",
      },
      {
        id: "2",
        image: "/investment-charts.png",
        caption: "Análise: onde investir em 2024? 📈",
        likes: "6.8K",
        comments: "387",
        date: "5 dias atrás",
      },
    ],
  },
]

interface InfluencerPageProps {
  params: {
    id: string
  }
}

export default function InfluencerPage({ params }: InfluencerPageProps) {
  const influencer = influencers.find((inf) => inf.id === params.id)

  if (!influencer) {
    notFound()
  }

  return (
    <div className="min-h-screen bg-background">
      <DashboardHeader />
      <InfluencerProfile influencer={influencer} />
    </div>
  )
}
